### ISSUE TITLE
Error when using client in a project that has a RestSharp Dependency >= 107.0.1

### ISSUE THREAD

**Issue by sjbrouillard** [merge-api/merge-hris-csharp-net#14]
I apologized if this has been answered either here or on the Merge support site, I have been unable to locate it. I'm happy to provide any additional information that I can to help address the issue.

I'm working with a client that has a dependency on RestSharp (they're currently using V108.0.2) in several of their private NuGet packages, so removing RestSharp as an indirect dependency is not a viable option for this project.

Before even working with the client project, I created a small sandbox POC to play around with the API, etc, and had no issues. When I started testing merge integration via this library in the main client project, I began getting the following error when making a call out to merge via the EmployeeApi - **_System.MissingMethodException: 'Method not found: 'Void RestSharp.RestRequest..ctor(RestSharp.Method)'.'_**

After a bit of digging, it became clear that any reference to RestSharp >= V107.0.1 either directly or indirectly causes this error to surface.

**_Recreation Steps:_**

1. Create a .NET 6 Console App
2. Create and configure a simple EmployeeAPI reference
3. Call the EmployeesListAsync method on the API - Should be successful. (see sample below)
4. Add the RestSharp package (>= V107.0.1) either directly or indirectly via another package reference
5. Make the same call as step 3 above - You should get the error described above

**_Simple Example Code:_**

```
var testConfig = new Configuration();
testConfig.BasePath = @"https://api.merge.dev/api/hris/v1";
testConfig.ApiKey.Add("Authorization", @"someValidApiKey);
testConfig.ApiKeyPrefix.Add("Authorization", "Bearer");

var testEmployeeApi = new EmployeesApi(testConfig);
var testList = await testEmployeeApi.EmployeesListAsync(someValidAccountToken);
```

**Comment by leewang0** [comment]
Hello Stephen,

We have two options here.

1. https://stackoverflow.com/a/42242382 indicates that you can create a new project in your client's solution which will let you use the older RestSharp dependency just for Merge's SDK, and you can then call that new project from other projects in your client's overall solution. The advantage here is that you can also add Merge-specific code into the new project for your client, and achieve better isolation. Can you explain if this is not an option for you?

2. We can release a snapshot version which uses a newer RestSharp dependency. As you noted, this is a breaking change since version 107+ of RestSharp is backwards incompatible, and we have used <=106 for a long time so our other customers may not be ready for this. We can pursue this if you need.

**Comment by sjbrouillard** [comment]
Hi Lee. Thanks for getting back to me on this. I was able to use a similar workaround to the one described in the Stack Overflow post and have something that will work in the short term. I assume that you will be addressing this in a more universal fashion with a major rev on the client sometime down the road? If so, I'd like to be kept in the loop on that and the timing, but am otherwise **not** in need of a snapshot version.

Thanks again for your quick response on this issue.
